id = "0002"
title = "allow git add for create issue"
description = ""
labels = []
priority = "medium"
assigned_to = ""
status = "in_progress"
closed = false
created_at = "2026-02-15"

[[comments]]
author = "glh@strand3.com"
date = "2026-02-15"
message = "Started work on this issue"
